### ISSUE TITLE
Show the plugin full screen

### ISSUE THREAD

**Issue by codeflyer** [nearform/mercurius-federation-info-graphiql-plugin#86]
A new design was made to improve the usability of the plugin.

https://www.figma.com/file/Qf8hgYpM5kUzItgVdesLbu/Federation-info?node-id=106%3A13535&t=XpsGV5ozdDJuoJoh-0

Create a full screen view of the plugin, according the design.

* Remove the `tab` view
* Close other windows of GQL when the plugin opens
* Reopen the closed view when the plugin close

**Comment by simoneb** [comment]
Pull request made to graphiql https://github.com/graphql/graphiql/pull/2929

**Comment by lasmil** [comment]
There is a way to still bypass the need of that PR. That PR is useful but for our plugin, we can "forcefully" hide that element. I will create a PR to showcase it

**Comment by simoneb** [comment]
@lasmil I saw that comment, but I'm not sure I understand what it means exactly, are they suggesting that we should use a different approach at rendering our plugin's UI?

**Comment by lasmil** [comment]
@simoneb let me try to explain.
Our approach to modify the graphiql library is useful in some scenarios, for example if we want to add additional styles to those panels, or if we want to individually toggle the visibility of them.

In our case, for the federation info plugin, we just want to hide that side panel entirely. This can be done purely with CSS, without modifying graphiql. JonathanAwesome (a collaborator in the graphiql PR) mentioned this example:
https://codesandbox.io/s/graphiql-full-view-plugin-eigzsu
This codebox contains an example of how this can be done.

Originally I was against removing CSS elements which are part of an external package (graphiql in this case). Class names are used to access these elements, which can be changed outside of our control (someone from graphiql decides to rename these classes).
Now, there is the option to avoid using class names and parse the document hierarchy (going from div to div), but this can be looked at if the above scenario happens (I highly doubt that they will rename their classes).

Apparently there is a wider discussion on that open graphiql PR. They/we need to see which is the best approach to allow panel styling, and the graphiql collaborators might ask additional changes to be applied. In the meantime, our solution of removing the panel using CSS works and this can be revisited if needed.

I linked a PR to this issue, it's in draft mode because I am still testing if nothing else is broken.

**Comment by lasmil** [comment]
After discussing with @matijagaspar and @andreaforni we decided that the full screen view will be implemented in another PR (issue will be created for this). The reasoning behind this is that we need a bit more complex functionality from graphiql - to provide a context which we can use to toggle the visibility of the panels.
The solution mentioned above only works in the frontend view but not in a built (dist) file ie using `npm run example`

The PR for this issue will contain the usage of material-ui and the removal of the tabs.
